favorite_fruits = ['strawberries', 'blueberries', 'peaches']
print(favorite_fruits)
favorite_fruits.append('kiwi')
print(favorite_fruits)
favorite_fruits.remove('strawberries')
print(favorite_fruits)
favorite_fruits.sort()
print(favorite_fruits)
favorite_fruits.reverse()
print(favorite_fruits)
